; PlatformIO Project Configuration for ESP32-S3 N16R8
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Serial Monitor & Upload Speeds
monitor_speed = 115200
upload_speed = 921600

; CRITICAL HARDWARE FLAGS FOR ESP32-S3 N16R8:
; 16MB Flash + 8MB Octal SPI PSRAM (OPI mode)
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.prsam_type = opi
board_upload.flash_size = 16MB
board_build.partitions = partitions_16MB.csv
extra_scripts = post:scripts/merge_bin.py

build_flags = 
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DCORE_DEBUG_LEVEL=3
    -DCONFIG_ESP32S3_SPIRAM_SUPPORT=1
